"""Retrain the embedding on Atom-SignalLab's OWN I/Q — the distribution the
Atomizer app actually feeds the classifier.

The rfgen-trained model did not transfer to SignalLab's I/Q (CW read as AM, FM as
BPSK). This retrains on a corpus generated by SignalLab's `synthesizeAnalyticComplexIq`
(see tools/generate-signallab-iq-corpus.ts), grouped into 7 I/Q-separable classes
that map to the app's protocol-leaf taxonomy:
    am · bluetooth · cw · dsss · fm · gsm · ofdm

Key alignment with the app: the app feeds CLEAN (noise-free, deterministic)
SignalLab I/Q, so prototypes and validation use clean preprocess, while the metric
is trained on lightly-augmented views (small AWGN/CFO/scale) for a robust space.

Run:  .venv-training/bin/python training/train_signallab.py
Exports src/embedding/assets/{embedding-weights,prototypes,parity-fixture,model-manifest}.json
"""

from __future__ import annotations

import copy
import json
import math
import os
import sys

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(__file__))
import preprocess as pp  # noqa: E402
import dataset as ds  # noqa: E402
from model import Embedding, INPUT_LEN, EMBED_DIM, N_FEATURES  # noqa: E402
from train import np_forward, embed_all, prototypes_from, nearest, sq_dist  # noqa: E402

SEED = 20260721
CORPUS = os.path.join(os.path.dirname(__file__), "artifacts", "signallab-corpus")
ASSET_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "embedding", "assets")
EPISODES = 6000
EVAL_EVERY = 1000
K_SHOT = 5
Q_QUERY = 5
AUG_PER_TRAIN = 4


def load_corpus():
    manifest = json.load(open(os.path.join(CORPUS, "corpus.json")))
    n = manifest["count"]
    L = manifest["sampleCount"]
    raw = np.fromfile(os.path.join(CORPUS, "corpus.f32"), dtype="<f4").reshape(n, L, 2)
    iq = raw[:, :, 0].astype(np.float64) + 1j * raw[:, :, 1].astype(np.float64)
    classes = sorted(manifest["classes"])
    cindex = {c: i for i, c in enumerate(classes)}
    y = np.array([cindex[it["cls"]] for it in manifest["items"]], dtype=np.int64)
    impaired = np.array([bool(it.get("impaired", False)) for it in manifest["items"]])
    return iq, y, impaired, classes


def build_pool(iq, y, idx, rng, scale_jitter=0.0):
    """Preprocess each corpus signal. Impairments are baked into the corpus
    (SignalLab's receiver model), so no extra augmentation here — only optional
    scale jitter for bandwidth-estimate robustness."""
    xs, fs, ys = [], [], []
    for i in idx:
        norm, _ = pp.preprocess(iq[i], scale_jitter=scale_jitter, rng=rng)
        xs.append(pp.to_channels(norm))
        fs.append(pp.iq_features(norm))
        ys.append(y[i])
    return (np.stack(xs).astype(np.float32), np.stack(fs).astype(np.float32),
            np.array(ys, dtype=np.int64))


def main():
    torch.manual_seed(SEED)
    np.random.seed(SEED)
    rng = np.random.default_rng(SEED)
    dev = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")

    iq, y, impaired, classes = load_corpus()
    n_classes = len(classes)
    print(f"device: {dev} | corpus {iq.shape} | impaired {int(impaired.sum())}/{len(impaired)} | classes {classes}")

    # Clean realizations -> prototype enrollment + validation (the app feeds clean
    # I/Q, so the space must be anchored on clean). Impaired realizations (+ the
    # remaining clean) -> train, so the metric is robust to real receiver/channel
    # variation. Split by realization to avoid leakage.
    clean_pos = rng.permutation(np.where(~impaired)[0])
    imp_pos = np.where(impaired)[0]
    n_en = int(0.30 * len(clean_pos))
    n_va = int(0.30 * len(clean_pos))
    en_idx = clean_pos[:n_en]
    va_idx = clean_pos[n_en:n_en + n_va]
    tr_idx = np.concatenate([clean_pos[n_en + n_va:], imp_pos])

    print("building pools ...")
    xtr, ftr, ytr = build_pool(iq, y, tr_idx, rng, scale_jitter=0.08)
    fmean = ftr.mean(0); fstd = ftr.std(0) + 1e-6
    ftr = (ftr - fmean) / fstd
    idx_by_class = ds.class_indices(ytr, n_classes)
    xen, fen, yen = build_pool(iq, y, en_idx, rng, scale_jitter=0.0)
    fen = (fen - fmean) / fstd
    xva, fva, yva = build_pool(iq, y, va_idx, rng, scale_jitter=0.0)
    fva = (fva - fmean) / fstd
    print(f"  train {xtr.shape}  enroll {xen.shape}  val {xva.shape}")

    net = Embedding(EMBED_DIM, N_FEATURES).to(dev)
    scale = torch.nn.Parameter(torch.tensor(10.0, device=dev))
    opt = torch.optim.Adam(list(net.parameters()) + [scale], lr=1e-3, weight_decay=2e-4)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=EPISODES)
    n_way = n_classes

    def eval_clean():
        protos = prototypes_from(embed_all(net, xen, fen, dev), yen, n_classes)
        pred, _ = nearest(embed_all(net, xva, fva, dev), protos)
        return float((pred == yva).mean())

    print(f"training {EPISODES} episodes ({n_way}-way {K_SHOT}-shot) ...")
    running, best_acc, best_state = 0.0, -1.0, None
    for ep in range(EPISODES):
        net.train()
        sx, sf, sl, qx, qf, ql = ds.sample_episode(xtr, ftr, idx_by_class, rng, n_way, K_SHOT, Q_QUERY)
        xb = torch.from_numpy(np.concatenate([sx, qx])).to(dev)
        fb = torch.from_numpy(np.concatenate([sf, qf])).to(dev)
        emb = net(xb, fb)
        se, qe = emb[: len(sx)], emb[len(sx):]
        protos = torch.stack([se[torch.from_numpy(sl).to(dev) == c].mean(0) for c in range(n_way)])
        logits = -sq_dist(qe, protos) * scale
        loss = torch.nn.functional.cross_entropy(logits, torch.from_numpy(ql).to(dev))
        opt.zero_grad(); loss.backward(); opt.step(); sched.step()
        running += loss.item()
        if (ep + 1) % 500 == 0:
            print(f"  ep {ep+1:5d}  loss {running/500:.4f}"); running = 0.0
        if (ep + 1) % EVAL_EVERY == 0:
            acc = eval_clean()
            tag = ""
            if acc > best_acc:
                best_acc, best_state = acc, copy.deepcopy(net.state_dict()); tag = "  <- best"
            print(f"    [val(clean) {acc:.3f}]{tag}")
    if best_state is not None:
        net.load_state_dict(best_state)

    # enroll + validate on clean
    emb_en = embed_all(net, xen, fen, dev)
    protos = prototypes_from(emb_en, yen, n_classes)
    emb_va = embed_all(net, xva, fva, dev)
    pred, dists = nearest(emb_va, protos)
    closed_acc = float((pred == yva).mean())
    nn_known = dists.min(1)
    # generous open-set threshold: the app can feed geometry outside the training
    # val distribution, so known signals sit farther than the clean-val spread.
    # Keep the safety valve, but do not flag the 7 known classes as unknown.
    thr = float(max(np.quantile(nn_known, 0.99) * 1.6, float(nn_known.max()) * 1.25))
    print(f"clean closed-set accuracy: {closed_acc:.3f}")
    print("per class:", {classes[c]: round(float((pred[yva == c] == c).mean()), 3) for c in range(n_classes)})

    # temperature (min NLL on clean val)
    best_T, best_nll = 1.0, math.inf
    for T in np.linspace(0.02, 2.0, 100):
        lg = -dists / T; lg -= lg.max(1, keepdims=True)
        p = np.exp(lg); p /= p.sum(1, keepdims=True)
        nll = -np.log(p[np.arange(len(yva)), yva] + 1e-12).mean()
        if nll < best_nll:
            best_nll, best_T = nll, float(T)

    weights = net.export_weights()
    weights["feat_mean"] = fmean.astype(float).tolist()
    weights["feat_std"] = fstd.astype(float).tolist()
    net.eval()
    with torch.no_grad():
        probe_x = xva[:12]
        torch_emb = net(torch.from_numpy(probe_x).to(dev), torch.from_numpy(fva[:12]).to(dev)).cpu().numpy()
    np_emb = np.stack([np_forward(probe_x[i], weights) for i in range(len(probe_x))])
    fold_err = float(np.abs(torch_emb - np_emb).max())
    print(f"BN-fold parity: max|dz| = {fold_err:.2e}")
    assert fold_err < 1e-4

    os.makedirs(ASSET_DIR, exist_ok=True)
    with open(os.path.join(ASSET_DIR, "embedding-weights.json"), "w") as f:
        json.dump({"input_len": INPUT_LEN, "embed_dim": EMBED_DIM, "n_features": N_FEATURES,
                   "preprocess": {"l_out": pp.L_OUT, "target_frac": pp.TARGET_FRAC, "nfft": pp.NFFT,
                                  "energy_edge": pp.ENERGY_EDGE, "noise_floor_scale": pp.NOISE_FLOOR_SCALE, "smooth": pp.SMOOTH},
                   **weights}, f)
    with open(os.path.join(ASSET_DIR, "prototypes.json"), "w") as f:
        json.dump({"classes": classes, "embed_dim": EMBED_DIM,
                   "prototypes": protos.astype(float).tolist(),
                   "unknown_threshold": thr, "temperature": best_T}, f)
    fwd_fixture = [{"input": xva[i].ravel().astype(float).tolist(), "embedding": np_emb[i].astype(float).tolist()}
                   for i in range(8)]
    # clean preprocess parity fixtures from raw corpus signals
    pre_fixture = []
    for c in [0, 1, 2]:
        gi = int(np.where(y == c)[0][0])
        norm, ctx = pp.preprocess(iq[gi], scale_jitter=0.0)
        pre_fixture.append({"class": classes[c],
                            "iq": np.stack([iq[gi].real, iq[gi].imag], 0).ravel().astype(float).tolist(),
                            "iq_len": int(len(iq[gi])),
                            "expected": pp.to_channels(norm).ravel().astype(float).tolist(),
                            "features": pp.iq_features(norm).astype(float).tolist(),
                            "center": ctx["center"], "bw": ctx["bw"]})
    with open(os.path.join(ASSET_DIR, "parity-fixture.json"), "w") as f:
        json.dump({"forward": fwd_fixture, "preprocess": pre_fixture}, f)
    with open(os.path.join(ASSET_DIR, "model-manifest.json"), "w") as f:
        json.dump({"seed": SEED, "source": "signallab-analytic-complex-iq", "classes": classes,
                   "episodes": EPISODES, "metrics": {"clean_closed_set_accuracy": closed_acc, "best_val_accuracy": best_acc},
                   "unknown_threshold": thr, "temperature": best_T}, f, indent=2)
    print("done. assets ->", os.path.relpath(ASSET_DIR))


if __name__ == "__main__":
    main()
