"""Evaluate a v4 fusion on held-out current SignalLab length/scale captures.

The evaluation corpus must be generated by
``tools/generate-current-signallab-scale-eval.ts`` through the public
``AtomizerMeasurementService``.  Physical scale is the service-requested
output sample-rate ratio (1x, 1.25x, 1.5x, 2x), not an evaluator-side array
resample.  Every available 4,096/8,192/16,384 prefix is run through the frozen
FFT-free time-domain frontend.

This is development evidence only.  It refuses release/sealed paths, requires
the exact current training corpus used by the candidate, checks held-out
phase/receiver/content separation, and never loads the consumed historical
test partition.
"""
from __future__ import annotations

import argparse
from dataclasses import dataclass
import hashlib
import json
import os
from pathlib import Path
import sys
import time
from typing import Any, Iterable, Mapping, Sequence

import numpy as np
import torch


HERE = Path(__file__).resolve().parent
V2 = HERE.parent
ZPLANE = V2.parent
TRAINING = ZPLANE.parent
REPO = TRAINING.parent
for path in (TRAINING, ZPLANE, V2, HERE):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import run_invariant_cnn_dev as device_runner  # noqa: E402
import current_source_data as corpus_data  # noqa: E402
import time_domain_invariant_patch_preprocess as td_preprocess  # noqa: E402
from invariant_fusion import CenteredInvariantFusion  # noqa: E402
from invariant_patch_cnn import (  # noqa: E402
    InvariantPatchCNN,
    InvariantPatchConfig,
)
from train import embed_all  # noqa: E402


EVALUATION_SCHEMA = "v4-current-service-length-scale-evaluation-v1"
CORPUS_SCHEMA = "current-signallab-service-scale-eval-v3"
FUSION_SCHEMA = "v4-current-source-development-fusion-v1"
TRUSTED_PROTOTYPE_SOURCE = "current"
TRUSTED_SOURCE_ROUTING_KIND = (
    "trusted_acquisition_source_to_prototype_source_v1"
)
PUBLIC_CLASSES = ("am", "bluetooth", "cw", "dsss", "fm", "gsm", "ofdm")
SCALE_FACTORS = (1.0, 1.25, 1.5, 2.0)
PREFIX_LENGTHS = (4_096, 8_192, 16_384)
LENGTH_REFERENCE = 8_192
SCALE_REFERENCE = 1.0
PRODUCTION_CAPTURE_BANDWIDTH_RULE = (
    "2 * abs(nativeCarrierOffsetHz) + signalBandwidthHz at every scale factor"
)
INFORMATIVE_PREFIX_CENTERED_RMS_FLOOR = 1e-4
PRE_IMPAIRMENT_PREFIX_ADMISSION_RULE = (
    "every service-clean scale cell has a finite, non-constant "
    "4,096-sample prefix with centered complex RMS >= 0.0001 before "
    "receiver impairment"
)
SCALE_FAMILY_CONTENT_UNIQUENESS_RULE = (
    "all four published valid-content SHA-256 values are pairwise distinct "
    "before publication"
)
SCALE_GENERATOR_PATH = "tools/generate-current-signallab-scale-eval.ts"
SCALE_GENERATOR_BUNDLE_PATH = (
    ".artifacts/current-scale-eval-generator/"
    "generate-current-signallab-scale-eval.js"
)
GENERATOR_LINEAGE_SCHEMA = "atom-classifier-generator-lineage-v1"
EXPECTED_SCALE_GENERATOR_SOURCE_SHA256 = (
    "1078576469a2679e567d09f71f4def8c8bc3a62873de0eb84e53f6fbaa785caf"
)
EXPECTED_SCALE_GENERATOR_BUNDLE_SHA256 = (
    "af2656c2e57b01f20466414c46a9e1c633286477277d0b8a4fc67463bec4089c"
)
EXPECTED_SIGNAL_LAB_GIT_COMMIT = (
    "94171baf31bfa62150d4e9684e1fe33e5a343dc0"
)
EXPECTED_SIGNAL_LAB_GIT_TREE = (
    "ccda4401748953bb6705776694b29b571d4c684d"
)
EXPECTED_SIGNAL_LAB_CONTRACT_SHA256 = (
    "e5ebc468495b027c8b91aceac8aaa9031ae3104b2306641a868fe9c1eaec842f"
)
EXPECTED_SIGNAL_LAB_GENERATOR_BINDING_SHA256 = (
    "c88f13a423cf0c78065e38f2ed380c86d483191df9799182689f45dcd2c8a8a4"
)
EXPECTED_SERVICE_PATH = (
    "AtomizerMeasurementService.selectProfile",
    "AtomizerMeasurementService.configureChannel",
    "MeasurementServiceContinuation(v2)",
    "AtomizerMeasurementService.acquireIq",
    "complexIqMeasurementSchema.parse",
)
HASH_PATTERN = frozenset("0123456789abcdef")


@dataclass(frozen=True)
class ScaleGeneratorLineageBinding:
    """Exact reviewed generator source and bundle accepted by one caller."""

    source_sha256: str
    bundle_sha256: str


DEFAULT_SCALE_GENERATOR_LINEAGE = ScaleGeneratorLineageBinding(
    source_sha256=EXPECTED_SCALE_GENERATOR_SOURCE_SHA256,
    bundle_sha256=EXPECTED_SCALE_GENERATOR_BUNDLE_SHA256,
)


def _fixed_public_class(profile: str) -> str:
    """Independently map the current fixed-profile catalog to public labels."""
    if profile.startswith("gsm-"):
        return "gsm"
    if profile == "wifi-hr-dsss-11m":
        return "dsss"
    if profile.startswith("bluetooth-"):
        return "bluetooth"
    if (
        profile.startswith("lte-")
        or profile.startswith("nr-")
        or profile == "wifi-ofdm-20m"
        or profile.startswith("wifi6-")
    ):
        return "ofdm"
    raise ValueError(f"unknown fixed SignalLab profile {profile!r}")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def _sha256_bytes(value: bytes | memoryview) -> str:
    return hashlib.sha256(value).hexdigest()


def _generator_lineage_binding(
    expected: ScaleGeneratorLineageBinding = DEFAULT_SCALE_GENERATOR_LINEAGE,
) -> str:
    if not isinstance(expected, ScaleGeneratorLineageBinding):
        raise TypeError(
            "expected scale generator lineage must be an exact binding object"
        )
    source_sha256 = _hash_string(
        expected.source_sha256,
        "expected scale generator source SHA-256",
    )
    bundle_sha256 = _hash_string(
        expected.bundle_sha256,
        "expected scale generator bundle SHA-256",
    )
    return hashlib.sha256(
        "\0".join(
            (
                GENERATOR_LINEAGE_SCHEMA,
                SCALE_GENERATOR_PATH,
                source_sha256,
                SCALE_GENERATOR_BUNDLE_PATH,
                bundle_sha256,
            )
        ).encode("utf-8")
    ).hexdigest()


def _validate_generator_lineage(
    manifest: Mapping[str, Any],
    expected: ScaleGeneratorLineageBinding = DEFAULT_SCALE_GENERATOR_LINEAGE,
) -> None:
    if not isinstance(expected, ScaleGeneratorLineageBinding):
        raise TypeError(
            "expected scale generator lineage must be an exact binding object"
        )
    source_sha256 = _hash_string(
        expected.source_sha256,
        "expected scale generator source SHA-256",
    )
    bundle_sha256 = _hash_string(
        expected.bundle_sha256,
        "expected scale generator bundle SHA-256",
    )
    if manifest.get("generatorPath") != SCALE_GENERATOR_PATH:
        raise ValueError("scale-eval generatorPath drifted")
    lineage = manifest.get("generatorLineage")
    if not isinstance(lineage, Mapping):
        raise ValueError("scale-eval generatorLineage must be an object")
    expected = {
        "schema": GENERATOR_LINEAGE_SCHEMA,
        "repository": "Atom-Classifier",
        "sourcePath": SCALE_GENERATOR_PATH,
        "sourceSha256": source_sha256,
        "bundlePath": SCALE_GENERATOR_BUNDLE_PATH,
        "bundleSha256": bundle_sha256,
        "sourceBundleBindingSha256": _generator_lineage_binding(expected),
    }
    for field, value in expected.items():
        if lineage.get(field) != value:
            raise ValueError(
                f"scale-eval generatorLineage.{field} drifted"
            )


def _jsonable(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, np.ndarray):
        return _jsonable(value.tolist())
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        value = float(value)
    if isinstance(value, float):
        return value if np.isfinite(value) else None
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, torch.device):
        return str(value)
    return value


def _write_json_exclusive(path: Path, payload: Any) -> None:
    if path.exists():
        raise FileExistsError(f"refusing to overwrite evaluation: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp-{os.getpid()}")
    try:
        with temporary.open("x", encoding="utf-8") as handle:
            json.dump(
                _jsonable(payload),
                handle,
                indent=2,
                sort_keys=True,
                allow_nan=False,
            )
            handle.write("\n")
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()


def reject_sensitive_path(path: str | Path, role: str) -> Path:
    """Resolve and reject release, sealed, or consumed-test locations."""
    resolved = Path(path).expanduser().resolve()
    components = [part.lower().replace("_", "-") for part in resolved.parts]
    if (
        any("release" in part for part in components)
        or any("sealed" in part for part in components)
        or any(
            "consumed-test" in part or "consumedtest" in part
            for part in components
        )
    ):
        raise ValueError(
            "current service scale evaluation refuses release, sealed, or "
            f"consumed-test {role} paths: {resolved}"
        )
    return resolved


def _read_json(path: Path, role: str) -> dict[str, Any]:
    if not path.is_file():
        raise FileNotFoundError(f"{role} is missing: {path}")
    with path.open(encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError(f"{role} must be a JSON object")
    return value


def _plain_artifact(
    directory: Path,
    filename: Any,
    field: str,
) -> Path:
    if (
        not isinstance(filename, str)
        or not filename
        or Path(filename).name != filename
    ):
        raise ValueError(f"{field} must be a plain artifact filename")
    path = (directory / filename).resolve()
    if path.parent != directory or not path.is_file():
        raise ValueError(f"{field} artifact is missing: {path}")
    return path


def _positive_integer(value: Any, field: str) -> int:
    if (
        isinstance(value, (bool, np.bool_))
        or not isinstance(value, (int, np.integer))
        or int(value) <= 0
    ):
        raise ValueError(f"{field} must be a positive integer")
    return int(value)


def _integer(value: Any, field: str) -> int:
    if (
        isinstance(value, (bool, np.bool_))
        or not isinstance(value, (int, np.integer))
    ):
        raise ValueError(f"{field} must be an integer")
    return int(value)


def _nonnegative_integer(value: Any, field: str) -> int:
    if (
        isinstance(value, (bool, np.bool_))
        or not isinstance(value, (int, np.integer))
        or int(value) < 0
    ):
        raise ValueError(f"{field} must be a non-negative integer")
    return int(value)


def _finite_float(value: Any, field: str) -> float:
    if isinstance(value, (bool, np.bool_)):
        raise ValueError(f"{field} must be finite")
    try:
        result = float(value)
    except (TypeError, ValueError, OverflowError) as exc:
        raise ValueError(f"{field} must be finite") from exc
    if not np.isfinite(result):
        raise ValueError(f"{field} must be finite")
    return result


def _nonempty_string(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{field} must be a non-empty string")
    return value


def _hash_string(value: Any, field: str, length: int = 64) -> str:
    if (
        not isinstance(value, str)
        or len(value) != length
        or any(character not in HASH_PATTERN for character in value)
    ):
        raise ValueError(f"{field} must be a lowercase {length * 4}-bit hash")
    return value


@dataclass(frozen=True)
class ScaleEvalRow:
    index: int
    class_name: str
    profile: str
    replay: str
    pair_id: str
    realization_index: int
    phase_native_sample: int
    receiver_preset: str
    channel_seed: int
    receiver_seed: int | None
    scale_factor: float
    scale_key: str
    scale_numerator: int
    scale_denominator: int
    native_sample_rate_hz: int
    sample_rate_hz: int
    native_carrier_offset_hz: int
    signal_bandwidth_hz: int
    capture_bandwidth_hz: int
    valid_sample_count: int
    available_lengths: tuple[int, ...]
    content_sha256: str
    stored_sha256: str


@dataclass
class ScaleEvalCorpus:
    directory: Path
    manifest_path: Path
    raw_path: Path
    manifest: dict[str, Any]
    raw: np.memmap
    rows: list[ScaleEvalRow]
    audit: dict[str, Any]

    def prefix(self, row: ScaleEvalRow, length: int) -> np.ndarray:
        if length not in row.available_lengths:
            raise ValueError(
                f"row {row.index} does not admit prefix {length}"
            )
        pair = np.asarray(self.raw[row.index, :length], dtype=np.float64)
        if pair.shape != (length, 2) or not np.isfinite(pair).all():
            raise ValueError(f"row {row.index} prefix {length} is invalid")
        return pair[:, 0] + 1j * pair[:, 1]


@dataclass
class FusionCandidate:
    directory: Path
    metrics_path: Path
    metrics: dict[str, Any]
    fusion: CenteredInvariantFusion
    prototypes: np.ndarray
    prototype_labels: np.ndarray
    prototype_sources: np.ndarray
    prototype_profiles: tuple[str, ...]
    classes: list[str]
    feature_mean: np.ndarray
    feature_std: np.ndarray
    patch_length: int
    patch_count: int
    target_frac: float
    artifact_hashes: dict[str, str]


def _optional_seed(value: Any, field: str) -> int | None:
    if value is None:
        return None
    return _nonnegative_integer(value, field)


def load_scale_eval_corpus(
    directory: str | Path,
    *,
    allow_unbound_smoke: bool = False,
    expected_generator_lineage: ScaleGeneratorLineageBinding = (
        DEFAULT_SCALE_GENERATOR_LINEAGE
    ),
) -> ScaleEvalCorpus:
    source = reject_sensitive_path(directory, "corpus")
    manifest_path = source / "scale_eval.json"
    manifest = _read_json(manifest_path, "scale-eval manifest")
    if manifest.get("schema") != CORPUS_SCHEMA:
        raise ValueError(
            f"scale-eval schema must be {CORPUS_SCHEMA!r}"
        )
    if manifest.get("generator") != CORPUS_SCHEMA:
        raise ValueError("scale-eval generator identity drifted")
    _validate_generator_lineage(manifest, expected_generator_lineage)
    required_literals = {
        "developmentOnly": True,
        "releaseEvidence": False,
        "sealedReleaseDataUsed": 0,
        "consumedHistoricalTestRowsUsed": 0,
        "lowLevelSynthesizerCalls": False,
        "frequencyTransformsUsed": False,
    }
    for field, expected in required_literals.items():
        if manifest.get(field) != expected:
            raise ValueError(
                f"scale-eval manifest {field} must be {expected!r}"
            )
    unbound_smoke = manifest.get("unboundSmoke")
    if not isinstance(unbound_smoke, bool):
        raise ValueError("scale-eval unboundSmoke must be a JSON boolean")
    reference_record = manifest.get("referenceCorpus")
    if unbound_smoke and not allow_unbound_smoke:
        raise ValueError("unbound smoke corpus is not evaluation evidence")
    if not unbound_smoke and not isinstance(reference_record, dict):
        raise ValueError("bound scale evaluation lacks referenceCorpus")
    held_out_contract = manifest.get("heldOutContract")
    if (
        not isinstance(held_out_contract, dict)
        or held_out_contract.get("referenceBound")
        is not (reference_record is not None)
    ):
        raise ValueError("scale-eval held-out reference contract drifted")
    if manifest.get("physicalScaleMethod") != (
        "AtomizerMeasurementService derived output sample-rate request"
    ):
        raise ValueError("scale evaluation was not service-rate derived")
    if (
        manifest.get("captureBandwidthRule")
        != PRODUCTION_CAPTURE_BANDWIDTH_RULE
    ):
        raise ValueError(
            "scale evaluation does not preserve production capture geometry"
        )
    if (
        manifest.get("informativePrefixCenteredRmsFloor")
        != INFORMATIVE_PREFIX_CENTERED_RMS_FLOOR
    ):
        raise ValueError(
            "scale evaluation informative-prefix RMS floor drifted"
        )
    if (
        manifest.get("preImpairmentPrefixAdmissionRule")
        != PRE_IMPAIRMENT_PREFIX_ADMISSION_RULE
    ):
        raise ValueError(
            "scale evaluation pre-impairment prefix admission drifted"
        )
    if (
        manifest.get("scaleFamilyContentUniquenessRule")
        != SCALE_FAMILY_CONTENT_UNIQUENESS_RULE
    ):
        raise ValueError(
            "scale evaluation family-content uniqueness contract drifted"
        )
    if manifest.get("servicePath") != list(EXPECTED_SERVICE_PATH):
        raise ValueError("scale evaluation public service path drifted")
    declared_scales = manifest.get("scaleFactors")
    if not isinstance(declared_scales, list):
        raise ValueError("scaleFactors must be an array")
    observed_scale_contract = tuple(
        _finite_float(row.get("value"), f"scaleFactors[{index}].value")
        if isinstance(row, dict)
        else float("nan")
        for index, row in enumerate(declared_scales)
    )
    if observed_scale_contract != SCALE_FACTORS:
        raise ValueError(
            f"scaleFactors must be exactly {SCALE_FACTORS}"
        )
    if tuple(manifest.get("prefixLengths", ())) != PREFIX_LENGTHS:
        raise ValueError(
            f"prefixLengths must be exactly {PREFIX_LENGTHS}"
        )
    storage = _positive_integer(
        manifest.get("storageSampleCount"),
        "storageSampleCount",
    )
    if storage != PREFIX_LENGTHS[-1]:
        raise ValueError("scale-eval storage must be 16,384 samples")
    count = _positive_integer(manifest.get("count"), "count")
    items = manifest.get("items")
    if not isinstance(items, list) or len(items) != count:
        raise ValueError("scale-eval count/items disagree")
    data_file = manifest.get("dataFile")
    raw_path = _plain_artifact(source, data_file, "dataFile")
    expected_size = count * storage * 2 * np.dtype("<f4").itemsize
    if raw_path.stat().st_size != expected_size:
        raise ValueError("scale-eval raw byte size disagrees with manifest")
    raw_sha256 = _sha256(raw_path)
    if raw_sha256 != _hash_string(
        manifest.get("dataSha256"), "dataSha256"
    ):
        raise ValueError("scale-eval raw SHA-256 disagrees with manifest")
    raw = np.memmap(
        raw_path,
        dtype="<f4",
        mode="r",
        shape=(count, storage, 2),
    )

    rows: list[ScaleEvalRow] = []
    pair_scale: dict[tuple[str, float], int] = {}
    content_owner: dict[str, int] = {}
    profile_classes: dict[str, str] = {}
    verified_padding_values = 0
    for index, value in enumerate(items):
        if not isinstance(value, dict):
            raise ValueError(f"scale-eval item {index} must be an object")
        if value.get("index") != index:
            raise ValueError(f"scale-eval item {index} index drifted")
        class_name = _nonempty_string(value.get("cls"), f"items[{index}].cls")
        profile = _nonempty_string(
            value.get("profile"), f"items[{index}].profile"
        )
        expected_class = _fixed_public_class(profile)
        if class_name != expected_class:
            raise ValueError(
                f"scale-eval profile {profile!r} must map to "
                f"{expected_class!r}, not {class_name!r}"
            )
        if value.get("profileId") != profile:
            raise ValueError(f"scale-eval item {index} profileId drifted")
        previous_class = profile_classes.get(profile)
        if previous_class is not None and previous_class != class_name:
            raise ValueError(f"profile {profile!r} crosses public classes")
        profile_classes[profile] = class_name
        replay = _nonempty_string(
            value.get("replay"), f"items[{index}].replay"
        )
        if replay not in {"cyclic", "one-shot"}:
            raise ValueError(f"items[{index}].replay is invalid")
        pair_id = _nonempty_string(
            value.get("pairId"), f"items[{index}].pairId"
        )
        scale = _finite_float(
            value.get("scaleFactor"), f"items[{index}].scaleFactor"
        )
        if scale not in SCALE_FACTORS:
            raise ValueError(f"items[{index}] has unplanned scale {scale}")
        pair_key = (pair_id, scale)
        if pair_key in pair_scale:
            raise ValueError(
                f"paired identity {pair_id!r} repeats scale {scale}"
            )
        pair_scale[pair_key] = index
        scale_numerator = _positive_integer(
            value.get("scaleNumerator"),
            f"items[{index}].scaleNumerator",
        )
        scale_denominator = _positive_integer(
            value.get("scaleDenominator"),
            f"items[{index}].scaleDenominator",
        )
        if scale_numerator / scale_denominator != scale:
            raise ValueError(f"items[{index}] scale rational disagrees")
        native_rate = _positive_integer(
            value.get("nativeSampleRateHz"),
            f"items[{index}].nativeSampleRateHz",
        )
        sample_rate = _positive_integer(
            value.get("sampleRateHz"),
            f"items[{index}].sampleRateHz",
        )
        native_carrier_offset = _integer(
            value.get("nativeCarrierOffsetHz"),
            f"items[{index}].nativeCarrierOffsetHz",
        )
        signal_bandwidth = _positive_integer(
            value.get("signalBandwidthHz"),
            f"items[{index}].signalBandwidthHz",
        )
        capture_bandwidth = _positive_integer(
            value.get("captureBandwidthHz"),
            f"items[{index}].captureBandwidthHz",
        )
        expected_capture_bandwidth = (
            2 * abs(native_carrier_offset) + signal_bandwidth
        )
        if capture_bandwidth != expected_capture_bandwidth:
            raise ValueError(
                f"items[{index}] capture bandwidth is not production-exact"
            )
        if capture_bandwidth > sample_rate:
            raise ValueError(
                f"items[{index}] capture bandwidth exceeds output sample rate"
            )
        if native_rate * scale_numerator % scale_denominator != 0:
            raise ValueError(f"items[{index}] output rate is non-integral")
        if (
            native_rate * scale_numerator // scale_denominator
            != sample_rate
        ):
            raise ValueError(f"items[{index}] output sample rate drifted")
        valid = _positive_integer(
            value.get("validSampleCount"),
            f"items[{index}].validSampleCount",
        )
        if valid > storage or valid < PREFIX_LENGTHS[0]:
            raise ValueError(f"items[{index}] validSampleCount is invalid")
        available = tuple(
            length for length in PREFIX_LENGTHS if length <= valid
        )
        if tuple(value.get("availablePrefixLengths", ())) != available:
            raise ValueError(f"items[{index}] available prefix list drifted")
        padding_flag = value.get("zeroPaddedAfterValidSampleCount")
        if padding_flag is not (valid < storage):
            raise ValueError(f"items[{index}] zero-padding flag drifted")
        valid_pairs = np.asarray(raw[index, :valid], dtype="<f4")
        if not np.isfinite(valid_pairs).all():
            raise ValueError(f"items[{index}] contains NaN or infinity")
        content_sha256 = _sha256_bytes(
            valid_pairs.tobytes(order="C")
        )
        if content_sha256 != _hash_string(
            value.get("contentSha256"),
            f"items[{index}].contentSha256",
        ):
            raise ValueError(f"items[{index}] valid content hash drifted")
        if content_sha256 in content_owner:
            raise ValueError(
                "scale-eval rows contain byte-identical valid content: "
                f"{content_owner[content_sha256]} and {index}"
            )
        content_owner[content_sha256] = index
        stored_sha256 = _sha256_bytes(
            np.asarray(raw[index], dtype="<f4").tobytes(order="C")
        )
        if stored_sha256 != _hash_string(
            value.get("storedSha256"),
            f"items[{index}].storedSha256",
        ):
            raise ValueError(f"items[{index}] stored content hash drifted")
        if valid < storage:
            tail = np.asarray(raw[index, valid:])
            if not np.all(tail == 0):
                raise ValueError(f"items[{index}] padded tail is nonzero")
            verified_padding_values += int(tail.size)
        receiver_seed = _optional_seed(
            value.get("receiverRealizationSeed"),
            f"items[{index}].receiverRealizationSeed",
        )
        receipt = value.get("measurementReceipt")
        if not isinstance(receipt, dict):
            raise ValueError(f"items[{index}] measurementReceipt is missing")
        if (
            receipt.get("samplesSha256") != content_sha256
            or receipt.get("sampleCount") != valid
            or receipt.get("sampleRateHz") != sample_rate
            or receipt.get("nativeSampleRateHz") != native_rate
            or receipt.get("nativeCarrierOffsetHz")
            != native_carrier_offset
            or receipt.get("signalBandwidthHz") != signal_bandwidth
            or receipt.get("captureBandwidthHz") != capture_bandwidth
            or receipt.get("receiverImpairment") != value.get("receiverPreset")
        ):
            raise ValueError(f"items[{index}] service receipt geometry drifted")
        transform_receipt = receipt.get("transformReceipt")
        if not isinstance(transform_receipt, dict):
            raise ValueError(f"items[{index}] transformReceipt is missing")
        if (
            transform_receipt.get("outputSamplesSha256") != content_sha256
            or transform_receipt.get("outputSampleRateHz") != sample_rate
            or transform_receipt.get("sourceSampleRateHz") != native_rate
            or transform_receipt.get("outputSampleCount") != valid
            or transform_receipt.get("outputStartSourceSampleNumerator")
            != str(value.get("phaseNativeSample"))
            or transform_receipt.get("outputStartSourceSampleDenominator")
            != "1"
        ):
            raise ValueError(
                f"items[{index}] transform receipt geometry drifted"
            )
        operations = transform_receipt.get("operations")
        if not isinstance(operations, list) or any(
            not isinstance(operation, dict) for operation in operations
        ):
            raise ValueError(f"items[{index}] transform operations are invalid")
        if scale != SCALE_REFERENCE and not any(
            operation.get("kind") == "resample"
            for operation in operations
        ):
            raise ValueError(
                f"items[{index}] derived scale lacks a resample receipt"
            )
        rows.append(
            ScaleEvalRow(
                index=index,
                class_name=class_name,
                profile=profile,
                replay=replay,
                pair_id=pair_id,
                realization_index=_nonnegative_integer(
                    value.get("realizationIndex"),
                    f"items[{index}].realizationIndex",
                ),
                phase_native_sample=_nonnegative_integer(
                    value.get("phaseNativeSample"),
                    f"items[{index}].phaseNativeSample",
                ),
                receiver_preset=_nonempty_string(
                    value.get("receiverPreset"),
                    f"items[{index}].receiverPreset",
                ),
                channel_seed=_nonnegative_integer(
                    value.get("receiverRealizationChannelSeed"),
                    f"items[{index}].receiverRealizationChannelSeed",
                ),
                receiver_seed=receiver_seed,
                scale_factor=scale,
                scale_key=_nonempty_string(
                    value.get("scaleFactorKey"),
                    f"items[{index}].scaleFactorKey",
                ),
                scale_numerator=scale_numerator,
                scale_denominator=scale_denominator,
                native_sample_rate_hz=native_rate,
                sample_rate_hz=sample_rate,
                native_carrier_offset_hz=native_carrier_offset,
                signal_bandwidth_hz=signal_bandwidth,
                capture_bandwidth_hz=capture_bandwidth,
                valid_sample_count=valid,
                available_lengths=available,
                content_sha256=content_sha256,
                stored_sha256=stored_sha256,
            )
        )

    pair_members: dict[str, list[ScaleEvalRow]] = {}
    for row in rows:
        pair_members.setdefault(row.pair_id, []).append(row)
    for pair_id, members in pair_members.items():
        if sorted(row.scale_factor for row in members) != list(SCALE_FACTORS):
            raise ValueError(
                f"paired identity {pair_id!r} lacks the full scale family"
            )
        member_content_hashes = [row.content_sha256 for row in members]
        if len(set(member_content_hashes)) != len(SCALE_FACTORS):
            raise ValueError(
                f"paired identity {pair_id!r} contains byte-identical "
                "scale cells"
            )
        invariant_fields = {
            (
                row.class_name,
                row.profile,
                row.replay,
                row.realization_index,
                row.phase_native_sample,
                row.receiver_preset,
                row.channel_seed,
                row.native_sample_rate_hz,
                row.native_carrier_offset_hz,
                row.signal_bandwidth_hz,
                row.capture_bandwidth_hz,
            )
            for row in members
        }
        if len(invariant_fields) != 1:
            raise ValueError(
                f"paired identity {pair_id!r} changes source/receiver identity"
            )

    source_record = manifest.get("source")
    if not isinstance(source_record, dict):
        raise ValueError("scale-eval source must be an object")
    expected_source = {
        "repository": "Atom-SignalLab",
        "gitCommit": EXPECTED_SIGNAL_LAB_GIT_COMMIT,
        "gitTree": EXPECTED_SIGNAL_LAB_GIT_TREE,
        "worktreeClean": True,
        "contractSha256": EXPECTED_SIGNAL_LAB_CONTRACT_SHA256,
        "generatorContractBindingSha256":
            EXPECTED_SIGNAL_LAB_GENERATOR_BINDING_SHA256,
    }
    for field, expected in expected_source.items():
        if source_record.get(field) != expected:
            raise ValueError(f"scale-eval source.{field} drifted")
    declared_profiles = manifest.get("profiles")
    declared_classes = manifest.get("classes")
    if (
        not isinstance(declared_profiles, list)
        or sorted(declared_profiles) != sorted(profile_classes)
        or not isinstance(declared_classes, list)
        or sorted(declared_classes)
        != sorted(set(profile_classes.values()))
    ):
        raise ValueError("scale-eval declared profile/class inventory drifted")
    if not unbound_smoke and len(declared_profiles) != 31:
        raise ValueError("bound scale evaluation must cover all 31 profiles")
    realizations_per_profile = _positive_integer(
        manifest.get("realizationsPerProfile"),
        "realizationsPerProfile",
    )
    pairs_per_profile = {
        profile: len(
            {
                row.pair_id
                for row in rows
                if row.profile == profile
            }
        )
        for profile in profile_classes
    }
    if any(
        count != realizations_per_profile
        for count in pairs_per_profile.values()
    ):
        raise ValueError("scale-eval realization count drifted by profile")
    audit = {
        "manifest_sha256": _sha256(manifest_path),
        "raw_sha256": raw_sha256,
        "count": count,
        "pair_count": len(pair_members),
        "profiles": sorted(profile_classes),
        "realizations_per_profile": realizations_per_profile,
        "pairs_per_profile": dict(sorted(pairs_per_profile.items())),
        "profile_public_class_map": dict(sorted(profile_classes.items())),
        "classes_present": sorted(set(profile_classes.values())),
        "scale_factors": list(SCALE_FACTORS),
        "prefix_lengths": list(PREFIX_LENGTHS),
        "verified_zero_padding_float_values": verified_padding_values,
        "unique_valid_content_hashes": len(content_owner),
        "source_git_commit": _hash_string(
            source_record.get("gitCommit"),
            "source.gitCommit",
            length=40,
        ),
        "source_git_tree": _hash_string(
            source_record.get("gitTree"),
            "source.gitTree",
            length=40,
        ),
        "reference_bound": isinstance(reference_record, dict),
        "unbound_smoke": unbound_smoke,
    }
    return ScaleEvalCorpus(
        directory=source,
        manifest_path=manifest_path,
        raw_path=raw_path,
        manifest=manifest,
        raw=raw,
        rows=rows,
        audit=audit,
    )


def _reference_manifest_and_raw(
    directory: Path,
) -> tuple[dict[str, Any], Path, Path, str, str]:
    manifest_path = directory / "corpus.json"
    manifest = _read_json(manifest_path, "current training manifest")
    data_file = manifest.get("dataFile", "corpus.f32")
    raw_path = _plain_artifact(directory, data_file, "reference dataFile")
    return (
        manifest,
        manifest_path,
        raw_path,
        _sha256(manifest_path),
        _sha256(raw_path),
    )


def validate_reference_separation(
    corpus: ScaleEvalCorpus,
    reference_directory: str | Path,
    *,
    candidate_current_audit: Mapping[str, Any],
) -> dict[str, Any]:
    reference = reject_sensitive_path(reference_directory, "reference corpus")
    (
        manifest,
        manifest_path,
        raw_path,
        manifest_sha256,
        raw_sha256,
    ) = _reference_manifest_and_raw(reference)
    if manifest.get("generator") != "current-signallab-service-corpus-v1":
        raise ValueError("reference is not the current service-path corpus")
    if candidate_current_audit.get("manifest_sha256") != manifest_sha256:
        raise ValueError(
            "reference manifest is not the candidate's current training corpus"
        )
    if candidate_current_audit.get("raw_sha256") != raw_sha256:
        raise ValueError(
            "reference raw data is not the candidate's current training corpus"
        )
    if (
        candidate_current_audit.get("profiles_present")
        != corpus.audit["profiles"]
        or candidate_current_audit.get("profile_public_class_map")
        != corpus.audit["profile_public_class_map"]
    ):
        raise ValueError(
            "scale evaluation profile/class inventory differs from the "
            "candidate current-source corpus"
        )
    if manifest.get("dataSha256") != raw_sha256:
        raise ValueError("reference raw SHA-256 disagrees with its manifest")
    recorded = corpus.manifest.get("referenceCorpus")
    if not isinstance(recorded, dict):
        raise ValueError("scale-eval corpus is not reference-bound")
    if recorded.get("manifestSha256") != manifest_sha256:
        raise ValueError("scale-eval reference manifest binding drifted")
    if recorded.get("rawSha256") != raw_sha256:
        raise ValueError("scale-eval reference raw binding drifted")
    items = manifest.get("items")
    count = _positive_integer(manifest.get("count"), "reference count")
    if not isinstance(items, list) or len(items) != count:
        raise ValueError("reference count/items disagree")
    content_hashes: set[str] = set()
    phases: dict[str, set[int]] = {}
    channel_seeds: set[int] = set()
    receiver_seeds: set[int] = set()
    for index, value in enumerate(items):
        if not isinstance(value, dict):
            raise ValueError(f"reference item {index} must be an object")
        content_hashes.add(
            _hash_string(
                value.get("contentSha256"),
                f"reference items[{index}].contentSha256",
            )
        )
        profile = _nonempty_string(
            value.get("profile"), f"reference items[{index}].profile"
        )
        phase = value.get("phaseNativeSample")
        if phase is not None:
            phases.setdefault(profile, set()).add(
                _nonnegative_integer(
                    phase, f"reference items[{index}].phaseNativeSample"
                )
            )
        channel_seed = value.get("receiverRealizationChannelSeed")
        if channel_seed is not None:
            channel_seeds.add(
                _nonnegative_integer(
                    channel_seed,
                    f"reference items[{index}].receiverRealizationChannelSeed",
                )
            )
        receiver_seed = value.get("receiverRealizationSeed")
        if receiver_seed is not None:
            receiver_seeds.add(
                _nonnegative_integer(
                    receiver_seed,
                    f"reference items[{index}].receiverRealizationSeed",
                )
            )
    content_collisions = [
        row.index for row in corpus.rows if row.content_sha256 in content_hashes
    ]
    if content_collisions:
        raise ValueError(
            "scale evaluation valid content occurs in current training corpus: "
            f"{content_collisions[:8]}"
        )
    cyclic_phase_collisions = [
        row.index
        for row in corpus.rows
        if row.replay == "cyclic"
        and row.phase_native_sample in phases.get(row.profile, set())
    ]
    if cyclic_phase_collisions:
        raise ValueError(
            "scale evaluation cyclic phases occur in current training corpus: "
            f"{cyclic_phase_collisions[:8]}"
        )
    one_shot_seed_collisions = [
        row.index
        for row in corpus.rows
        if row.replay == "one-shot"
        and (
            row.channel_seed in channel_seeds
            or (
                row.receiver_seed is not None
                and row.receiver_seed in receiver_seeds
            )
        )
    ]
    if one_shot_seed_collisions:
        raise ValueError(
            "scale evaluation one-shot receiver identity occurs in training: "
            f"{one_shot_seed_collisions[:8]}"
        )
    reference_source = manifest.get("source")
    if not isinstance(reference_source, dict):
        raise ValueError("reference source must be an object")
    if (
        corpus.audit["source_git_commit"]
        != reference_source.get("gitCommit")
        or corpus.audit["source_git_tree"]
        != reference_source.get("gitTree")
    ):
        raise ValueError("scale evaluation and reference SignalLab source differ")
    return {
        "directory": reference,
        "manifest": manifest_path.name,
        "raw": raw_path.name,
        "manifest_sha256": manifest_sha256,
        "raw_sha256": raw_sha256,
        "reference_rows": count,
        "reference_content_hashes": len(content_hashes),
        "content_collision_count": 0,
        "cyclic_phase_collision_count": 0,
        "one_shot_receiver_seed_collision_count": 0,
        "candidate_current_audit_match": True,
        "signal_lab_source_match": True,
    }


def _load_numpy_vector(
    path: Path,
    field: str,
    *,
    positive: bool = False,
) -> np.ndarray:
    value = np.asarray(np.load(path, allow_pickle=False), dtype=np.float32)
    if value.ndim != 1 or value.size == 0 or not np.isfinite(value).all():
        raise ValueError(f"{field} must be a finite nonempty vector")
    if positive and np.any(value <= 0):
        raise ValueError(f"{field} must be strictly positive")
    return value


def _load_torch_state(path: Path) -> Mapping[str, torch.Tensor]:
    try:
        value = torch.load(path, map_location="cpu", weights_only=True)
    except TypeError:  # pragma: no cover - only for older supported Torch
        value = torch.load(path, map_location="cpu")
    if not isinstance(value, Mapping):
        raise ValueError("fusion state_dict must be a mapping")
    for name, tensor in value.items():
        if not isinstance(name, str) or not isinstance(tensor, torch.Tensor):
            raise ValueError("fusion state_dict entries must be named tensors")
        if (tensor.is_floating_point() or tensor.is_complex()) and not bool(
            torch.isfinite(tensor).all()
        ):
            raise ValueError(f"fusion state tensor {name!r} is non-finite")
    return value


def load_fusion_candidate(directory: str | Path) -> FusionCandidate:
    source = reject_sensitive_path(directory, "fusion candidate")
    metrics_path = source / "dev_metrics.json"
    metrics = _read_json(metrics_path, "fusion dev_metrics.json")
    required_literals = {
        "status": "complete",
        "development_only": True,
        "release_evidence": False,
        "sealed_release_data_used": 0,
        "consumed_historical_test_rows_used": 0,
        "consumed_test_rows_exposed": 0,
        "encoder": "fusion",
    }
    for field, expected in required_literals.items():
        if metrics.get(field) != expected:
            raise ValueError(
                f"fusion metrics {field} must be {expected!r}"
            )
    run_configuration = metrics.get("run_configuration")
    if (
        not isinstance(run_configuration, dict)
        or run_configuration.get("schema") != FUSION_SCHEMA
    ):
        raise ValueError(f"fusion schema must be {FUSION_SCHEMA!r}")
    frontend = metrics.get("frontend")
    if (
        not isinstance(frontend, dict)
        or frontend.get("uses_frequency_transform") is not False
        or frontend.get("version") != "invariant-patch-time-domain-v1"
    ):
        raise ValueError("candidate frontend is not the FFT-free v4 frontend")
    artifacts = metrics.get("artifacts")
    if not isinstance(artifacts, dict):
        raise ValueError("fusion metrics artifacts must be an object")
    artifact_keys = (
        "state_dict",
        "prototype_bank",
        "prototype_labels",
        "prototype_metadata",
        "real_center",
        "complex_center",
        "feature_mean",
        "feature_std",
    )
    paths: dict[str, Path] = {}
    hashes: dict[str, str] = {"dev_metrics.json": _sha256(metrics_path)}
    for key in artifact_keys:
        path = _plain_artifact(source, artifacts.get(key), f"artifacts.{key}")
        expected_hash = _hash_string(
            artifacts.get(f"{key}_sha256"),
            f"artifacts.{key}_sha256",
        )
        actual_hash = _sha256(path)
        if actual_hash != expected_hash:
            raise ValueError(f"fusion artifact {key} hash drifted")
        paths[key] = path
        hashes[path.name] = actual_hash

    architecture = metrics.get("architecture")
    if not isinstance(architecture, dict):
        raise ValueError("fusion architecture must be an object")
    real_architecture = architecture.get("real")
    complex_architecture = architecture.get("complex")
    if not isinstance(real_architecture, dict) or not isinstance(
        complex_architecture, dict
    ):
        raise ValueError("fusion architecture lacks branch configurations")
    try:
        real_config = InvariantPatchConfig(**real_architecture).validate()
        complex_config = InvariantPatchConfig(**complex_architecture).validate()
    except (TypeError, ValueError) as exc:
        raise ValueError("fusion branch architecture is invalid") from exc
    if real_config.encoder != "real" or complex_config.encoder != "complex":
        raise ValueError("fusion branch encoder identities drifted")
    real_center = _load_numpy_vector(paths["real_center"], "real center")
    complex_center = _load_numpy_vector(
        paths["complex_center"], "complex center"
    )
    fusion_contract = metrics.get("fusion")
    if not isinstance(fusion_contract, dict):
        raise ValueError("fusion contract must be an object")
    fusion = CenteredInvariantFusion(
        InvariantPatchCNN(real_config),
        InvariantPatchCNN(complex_config),
        real_center,
        complex_center,
        alpha_real=_finite_float(
            fusion_contract.get("alpha_real"), "fusion.alpha_real"
        ),
        alpha_complex=_finite_float(
            fusion_contract.get("alpha_complex"), "fusion.alpha_complex"
        ),
        weight_real=_finite_float(
            fusion_contract.get("weight_real"), "fusion.weight_real"
        ),
        eps=_finite_float(fusion_contract.get("eps"), "fusion.eps"),
    )
    fusion.load_state_dict(_load_torch_state(paths["state_dict"]), strict=True)
    fusion.eval()
    if not np.array_equal(
        fusion.real_center.detach().cpu().numpy(), real_center
    ) or not np.array_equal(
        fusion.complex_center.detach().cpu().numpy(), complex_center
    ):
        raise ValueError(
            "fusion state centers disagree with the standalone center assets"
        )
    if fusion.config() != architecture:
        raise ValueError(
            "loaded fusion state/config disagrees with architecture metadata"
        )

    prototypes = np.asarray(
        np.load(paths["prototype_bank"], allow_pickle=False),
        dtype=np.float32,
    )
    labels = np.asarray(
        np.load(paths["prototype_labels"], allow_pickle=False),
        dtype=np.int64,
    )
    if (
        prototypes.ndim != 2
        or prototypes.shape[0] == 0
        or prototypes.shape[1] != fusion.embed_dim
        or not np.isfinite(prototypes).all()
    ):
        raise ValueError("fusion prototype bank geometry is invalid")
    if labels.shape != (len(prototypes),):
        raise ValueError("fusion prototype labels geometry is invalid")
    prototype_metadata = _read_json(
        paths["prototype_metadata"], "fusion prototype metadata"
    )
    classes = prototype_metadata.get("classes")
    if (
        not isinstance(classes, list)
        or tuple(classes) != PUBLIC_CLASSES
    ):
        raise ValueError("fusion classes must be the canonical seven classes")
    classes = list(classes)
    if np.any(labels < 0) or np.any(labels >= len(classes)):
        raise ValueError("fusion prototype labels are out of range")
    if set(int(value) for value in labels) != set(range(len(classes))):
        raise ValueError("fusion prototype bank lacks a public class")
    if prototype_metadata.get(
        "prototype_public_class_indices"
    ) != labels.tolist():
        raise ValueError("fusion prototype label metadata drifted")
    groups = prototype_metadata.get("groups")
    if not isinstance(groups, list) or len(groups) != len(prototypes):
        raise ValueError("fusion prototype groups do not align with bank rows")
    sources: list[str] = []
    profiles: list[str] = []
    seen: set[tuple[str, str]] = set()
    current_profiles: set[str] = set()
    for index, group in enumerate(groups):
        if not isinstance(group, dict):
            raise ValueError(f"fusion prototype group {index} is invalid")
        source_name = group.get("source")
        profile = group.get("profile")
        if (
            source_name not in {"current", "historical"}
            or not isinstance(profile, str)
            or not profile
        ):
            raise ValueError(
                f"fusion prototype group {index} source/profile is invalid"
            )
        key = (source_name, profile)
        if key in seen:
            raise ValueError(f"fusion prototype group {key} is duplicated")
        seen.add(key)
        public_class = group.get("public_class")
        if public_class != classes[int(labels[index])]:
            raise ValueError(
                f"fusion prototype group {index} label mapping drifted"
            )
        if source_name == TRUSTED_PROTOTYPE_SOURCE:
            expected_class = (
                corpus_data.CURRENT_PROFILE_PUBLIC_CLASS_MAP.get(profile)
            )
            if expected_class is None or public_class != expected_class:
                raise ValueError(
                    f"fusion current prototype {profile} is not canonically "
                    "mapped"
                )
            current_profiles.add(profile)
        sources.append(source_name)
        profiles.append(profile)
    expected_current_profiles = set(
        corpus_data.CURRENT_PROFILE_PUBLIC_CLASS_MAP
    )
    if current_profiles != expected_current_profiles:
        raise ValueError(
            "fusion current prototype source lacks the exact 31-profile bank"
        )
    source_array = np.asarray(sources, dtype=object)
    current_mask = source_array == TRUSTED_PROTOTYPE_SOURCE
    current_supported = {
        classes[int(label)] for label in labels[current_mask]
    }
    if current_supported != set(corpus_data.CURRENT_CLASSES):
        raise ValueError(
            "fusion current prototype source class support drifted"
        )
    feature_mean = _load_numpy_vector(
        paths["feature_mean"], "feature mean"
    )
    feature_std = _load_numpy_vector(
        paths["feature_std"], "feature std", positive=True
    )
    if (
        feature_mean.shape != feature_std.shape
        or feature_mean.shape != (real_config.n_features,)
    ):
        raise ValueError("fusion feature moments geometry is invalid")
    matched_contract = metrics.get("matched_branch_contract")
    if not isinstance(matched_contract, dict):
        raise ValueError("fusion matched_branch_contract is missing")
    arguments = matched_contract.get("arguments_without_encoder")
    if not isinstance(arguments, dict):
        raise ValueError("fusion branch argument contract is missing")
    patch_length = _positive_integer(
        arguments.get("patch_length"), "patch_length"
    )
    patch_count = _positive_integer(
        arguments.get("patch_count"), "patch_count"
    )
    target_frac = _finite_float(arguments.get("target_frac"), "target_frac")
    if (
        patch_length != real_config.patch_length
        or patch_count != real_config.patch_count
        or not 0.0 < target_frac < 1.0
    ):
        raise ValueError("candidate preprocessing arguments drifted")
    data_audit = metrics.get("data_audit")
    if not isinstance(data_audit, dict) or not isinstance(
        data_audit.get("current"), dict
    ):
        raise ValueError("candidate current data audit is missing")
    if data_audit.get("consumed_test_rows_exposed") != 0:
        raise ValueError("candidate audit exposed consumed historical test rows")
    return FusionCandidate(
        directory=source,
        metrics_path=metrics_path,
        metrics=metrics,
        fusion=fusion,
        prototypes=prototypes,
        prototype_labels=labels,
        prototype_sources=source_array,
        prototype_profiles=tuple(profiles),
        classes=classes,
        feature_mean=feature_mean,
        feature_std=feature_std,
        patch_length=patch_length,
        patch_count=patch_count,
        target_frac=target_frac,
        artifact_hashes=hashes,
    )


def predict_from_profile_bank(
    embeddings: np.ndarray,
    prototypes: np.ndarray,
    prototype_labels: np.ndarray,
    n_classes: int,
    *,
    prototype_sources: Sequence[str],
    trusted_source: str,
) -> tuple[np.ndarray, np.ndarray]:
    value = np.asarray(embeddings, dtype=np.float32)
    bank = np.asarray(prototypes, dtype=np.float32)
    labels = np.asarray(prototype_labels, dtype=np.int64)
    sources = np.asarray(prototype_sources, dtype=object)
    if trusted_source not in {"current", "historical"}:
        raise ValueError("trusted_source must be current or historical")
    if (
        value.ndim != 2
        or bank.ndim != 2
        or value.shape[1] != bank.shape[1]
        or labels.shape != (len(bank),)
        or sources.shape != (len(bank),)
    ):
        raise ValueError("embedding/prototype geometry disagrees")
    if (
        n_classes < 2
        or np.any(labels < 0)
        or np.any(labels >= n_classes)
    ):
        raise ValueError("prototype class labels are invalid")
    admitted = sources == trusted_source
    if not np.any(admitted):
        raise ValueError(
            f"prototype bank has no rows for trusted source {trusted_source}"
        )
    prototype_distance = (
        (value[:, None, :] - bank[None, :, :]) ** 2
    ).sum(axis=-1)
    class_distance = np.full(
        (len(value), n_classes), np.inf, dtype=np.float32
    )
    for class_index in range(n_classes):
        mask = admitted & (labels == class_index)
        if not np.any(mask):
            continue
        class_distance[:, class_index] = prototype_distance[:, mask].min(
            axis=1
        )
    if not np.any(np.isfinite(class_distance)):
        raise ValueError(
            f"trusted source {trusted_source} supports no public class"
        )
    return class_distance.argmin(axis=1), class_distance


def classification_report(
    prediction: np.ndarray,
    labels: np.ndarray,
    classes: Sequence[str],
    profiles: Sequence[str],
) -> dict[str, Any]:
    predicted = np.asarray(prediction, dtype=np.int64)
    truth = np.asarray(labels, dtype=np.int64)
    profile_array = np.asarray(profiles, dtype=object)
    n_classes = len(classes)
    if (
        truth.ndim != 1
        or predicted.shape != truth.shape
        or profile_array.shape != truth.shape
        or len(truth) == 0
        or n_classes < 2
        or np.any(truth < 0)
        or np.any(truth >= n_classes)
        or np.any(predicted < 0)
        or np.any(predicted >= n_classes)
    ):
        raise ValueError("classification report inputs are invalid")
    confusion = np.zeros((n_classes, n_classes), dtype=np.int64)
    np.add.at(confusion, (truth, predicted), 1)
    per_class: dict[str, dict[str, Any]] = {}
    recalls: list[float | None] = []
    for class_index, class_name in enumerate(classes):
        count = int(np.sum(confusion[class_index]))
        recall = (
            float(confusion[class_index, class_index] / count)
            if count
            else None
        )
        recalls.append(recall)
        per_class[class_name] = {
            "count": count,
            "recall": recall,
            "predicted_as": {
                classes[predicted_index]: int(value)
                for predicted_index, value in enumerate(
                    confusion[class_index]
                )
                if int(value) > 0
            },
        }
    present = [value for value in recalls if value is not None]
    if not present:
        raise AssertionError("nonempty truth has no present class")
    per_profile: dict[str, dict[str, Any]] = {}
    for profile in sorted(str(value) for value in np.unique(profile_array)):
        mask = profile_array == profile
        profile_truth = np.unique(truth[mask])
        if len(profile_truth) != 1:
            raise ValueError(f"profile {profile!r} crosses public classes")
        label = int(profile_truth[0])
        profile_prediction = predicted[mask]
        per_profile[profile] = {
            "class": classes[label],
            "count": int(np.sum(mask)),
            "accuracy": float(np.mean(profile_prediction == label)),
            "predicted_as": {
                classes[class_index]: int(np.sum(profile_prediction == class_index))
                for class_index in range(n_classes)
                if np.any(profile_prediction == class_index)
            },
        }
    return {
        "count": len(truth),
        "accuracy": float(np.mean(predicted == truth)),
        "present_class_balanced_accuracy": float(np.mean(present)),
        "all_public_class_balanced_accuracy": float(
            np.mean([0.0 if value is None else value for value in recalls])
        ),
        "present_class_count": len(present),
        "per_class": per_class,
        "per_profile": per_profile,
        "confusion_matrix": {
            "rows_truth_columns_prediction": list(classes),
            "values": confusion.tolist(),
        },
    }


@dataclass(frozen=True)
class CellInference:
    factor: float
    length: int
    pair_ids: tuple[str, ...]
    labels: np.ndarray
    predictions: np.ndarray
    embeddings: np.ndarray
    profiles: tuple[str, ...]


def paired_invariance_report(
    left: CellInference,
    right: CellInference,
    classes: Sequence[str],
) -> dict[str, Any]:
    left_index = {pair_id: index for index, pair_id in enumerate(left.pair_ids)}
    right_index = {
        pair_id: index for index, pair_id in enumerate(right.pair_ids)
    }
    if (
        len(left_index) != len(left.pair_ids)
        or len(right_index) != len(right.pair_ids)
    ):
        raise ValueError("paired cells contain duplicate paired identities")
    common = sorted(set(left_index) & set(right_index))
    if not common:
        raise ValueError("paired invariance report has no common identities")
    left_positions = np.asarray(
        [left_index[pair_id] for pair_id in common], dtype=np.int64
    )
    right_positions = np.asarray(
        [right_index[pair_id] for pair_id in common], dtype=np.int64
    )
    left_labels = left.labels[left_positions]
    right_labels = right.labels[right_positions]
    if not np.array_equal(left_labels, right_labels):
        raise ValueError("paired identities change public class")
    left_embedding = np.asarray(
        left.embeddings[left_positions], dtype=np.float64
    )
    right_embedding = np.asarray(
        right.embeddings[right_positions], dtype=np.float64
    )
    if left_embedding.shape != right_embedding.shape:
        raise ValueError("paired embedding shapes disagree")
    left_norm = np.linalg.norm(left_embedding, axis=1)
    right_norm = np.linalg.norm(right_embedding, axis=1)
    if np.any(left_norm <= 0) or np.any(right_norm <= 0):
        raise ValueError("paired embeddings contain a zero vector")
    cosine = np.sum(left_embedding * right_embedding, axis=1) / (
        left_norm * right_norm
    )
    if not np.isfinite(cosine).all():
        raise ValueError("paired embedding cosine is non-finite")
    agreement = (
        left.predictions[left_positions]
        == right.predictions[right_positions]
    )
    per_class: dict[str, dict[str, Any]] = {}
    for class_index, class_name in enumerate(classes):
        mask = left_labels == class_index
        if not np.any(mask):
            per_class[class_name] = {
                "count": 0,
                "prediction_agreement": None,
                "embedding_cosine_mean": None,
            }
            continue
        per_class[class_name] = {
            "count": int(np.sum(mask)),
            "prediction_agreement": float(np.mean(agreement[mask])),
            "embedding_cosine_mean": float(np.mean(cosine[mask])),
        }
    return {
        "pair_count": len(common),
        "pair_identity_sha256": hashlib.sha256(
            json.dumps(
                common,
                sort_keys=True,
                separators=(",", ":"),
            ).encode("utf-8")
        ).hexdigest(),
        "prediction_agreement": float(np.mean(agreement)),
        "embedding_cosine_mean": float(np.mean(cosine)),
        "embedding_cosine_p05": float(np.quantile(cosine, 0.05)),
        "embedding_cosine_min": float(np.min(cosine)),
        "per_class": per_class,
    }


def _preprocess_rows(
    corpus: ScaleEvalCorpus,
    rows: Sequence[ScaleEvalRow],
    length: int,
    candidate: FusionCandidate,
) -> tuple[np.ndarray, np.ndarray, dict[str, Any]]:
    packed_values: list[np.ndarray] = []
    feature_values: list[np.ndarray] = []
    bandwidths: list[float] = []
    centers: list[float] = []
    for row in rows:
        try:
            packed, raw_features, context = td_preprocess.preprocess(
                corpus.prefix(row, length),
                patch_length=candidate.patch_length,
                patch_count=candidate.patch_count,
                target_frac=candidate.target_frac,
            )
        except Exception as exc:
            raise ValueError(
                f"FFT-free preprocessing failed for row {row.index} "
                f"at length {length}"
            ) from exc
        if context.get("uses_frequency_transform") is not False:
            raise AssertionError("scale evaluator admitted a frequency transform")
        packed_value = np.asarray(packed, dtype=np.float32)
        raw_feature_value = np.asarray(raw_features, dtype=np.float32)
        if raw_feature_value.shape != candidate.feature_mean.shape:
            raise ValueError("preprocessor feature geometry drifted")
        feature_value = (
            raw_feature_value - candidate.feature_mean
        ) / candidate.feature_std
        if (
            not np.isfinite(packed_value).all()
            or not np.isfinite(feature_value).all()
        ):
            raise ValueError("preprocessor emitted a non-finite value")
        packed_values.append(packed_value)
        feature_values.append(feature_value.astype(np.float32, copy=False))
        bandwidths.append(_finite_float(context.get("bw"), "context.bw"))
        centers.append(_finite_float(context.get("center"), "context.center"))
    return (
        np.stack(packed_values).astype(np.float32, copy=False),
        np.stack(feature_values).astype(np.float32, copy=False),
        {
            "count": len(rows),
            "all_fft_free": True,
            "bandwidth_min": float(np.min(bandwidths)),
            "bandwidth_median": float(np.median(bandwidths)),
            "bandwidth_max": float(np.max(bandwidths)),
            "center_min": float(np.min(centers)),
            "center_median": float(np.median(centers)),
            "center_max": float(np.max(centers)),
        },
    )


def _concatenate_cells(
    cells: Iterable[CellInference],
) -> CellInference:
    values = list(cells)
    if not values:
        raise ValueError("cannot concatenate an empty cell population")
    return CellInference(
        factor=float("nan"),
        length=-1,
        pair_ids=tuple(
            f"{cell.factor}:{cell.length}:{pair_id}"
            for cell in values
            for pair_id in cell.pair_ids
        ),
        labels=np.concatenate([cell.labels for cell in values]),
        predictions=np.concatenate([cell.predictions for cell in values]),
        embeddings=np.concatenate([cell.embeddings for cell in values]),
        profiles=tuple(
            profile for cell in values for profile in cell.profiles
        ),
    )


def _report_for_cell(
    cell: CellInference,
    classes: Sequence[str],
) -> dict[str, Any]:
    report = classification_report(
        cell.predictions,
        cell.labels,
        classes,
        cell.profiles,
    )
    normalized = cell.embeddings / np.maximum(
        np.linalg.norm(cell.embeddings, axis=1, keepdims=True),
        1e-12,
    )
    similarity = normalized @ normalized.T
    upper = similarity[np.triu_indices(len(similarity), k=1)]
    report["embedding_geometry"] = {
        "dimension": int(cell.embeddings.shape[1]),
        "mean_pairwise_cosine": (
            float(np.mean(upper)) if len(upper) else None
        ),
        "all_finite": bool(np.isfinite(cell.embeddings).all()),
    }
    return report


def evaluate(
    corpus: ScaleEvalCorpus,
    candidate: FusionCandidate,
    device: torch.device,
    *,
    batch_size: int,
) -> dict[str, Any]:
    if batch_size <= 0:
        raise ValueError("batch_size must be positive")
    class_index = {
        name: index for index, name in enumerate(candidate.classes)
    }
    missing_classes = sorted(
        {row.class_name for row in corpus.rows} - set(class_index)
    )
    if missing_classes:
        raise ValueError(
            f"scale corpus classes absent from candidate: {missing_classes}"
        )
    trusted_mask = (
        candidate.prototype_sources == TRUSTED_PROTOTYPE_SOURCE
    )
    if not np.any(trusted_mask):
        raise ValueError(
            "candidate has no current prototype bank for SignalLab scale "
            "evaluation"
        )
    supported_by_trusted_source = {
        candidate.classes[int(label)]
        for label in candidate.prototype_labels[trusted_mask]
    }
    missing_trusted_classes = sorted(
        {row.class_name for row in corpus.rows}
        - supported_by_trusted_source
    )
    if missing_trusted_classes:
        raise ValueError(
            "current prototype bank cannot classify scale corpus classes: "
            f"{missing_trusted_classes}"
        )
    fusion = candidate.fusion.to(device).eval()
    cells: dict[tuple[float, int], CellInference] = {}
    cell_reports: dict[str, dict[str, Any]] = {}
    geometry_reports: dict[str, dict[str, Any]] = {}
    for factor in SCALE_FACTORS:
        for length in PREFIX_LENGTHS:
            rows = [
                row
                for row in corpus.rows
                if row.scale_factor == factor
                and length in row.available_lengths
            ]
            if not rows:
                continue
            rows.sort(key=lambda row: row.pair_id)
            packed, features, geometry = _preprocess_rows(
                corpus, rows, length, candidate
            )
            embeddings = embed_all(
                fusion,
                packed,
                features,
                device,
                batch=batch_size,
            ).astype(np.float32, copy=False)
            prediction, _distance = predict_from_profile_bank(
                embeddings,
                candidate.prototypes,
                candidate.prototype_labels,
                len(candidate.classes),
                prototype_sources=candidate.prototype_sources,
                trusted_source=TRUSTED_PROTOTYPE_SOURCE,
            )
            cell = CellInference(
                factor=factor,
                length=length,
                pair_ids=tuple(row.pair_id for row in rows),
                labels=np.asarray(
                    [class_index[row.class_name] for row in rows],
                    dtype=np.int64,
                ),
                predictions=prediction.astype(np.int64, copy=False),
                embeddings=embeddings,
                profiles=tuple(row.profile for row in rows),
            )
            cells[(factor, length)] = cell
            key = f"scale={factor:g},length={length}"
            cell_reports[key] = {
                "scale_factor": factor,
                "prefix_length": length,
                **_report_for_cell(cell, candidate.classes),
            }
            geometry_reports[key] = geometry
            print(
                "[v4 current scale] "
                f"scale={factor:g} length={length} rows={len(rows)} "
                "present-bal="
                f"{cell_reports[key]['present_class_balanced_accuracy']:.4f}",
                flush=True,
            )

    expected_cells = {
        (factor, length)
        for factor in SCALE_FACTORS
        for length in PREFIX_LENGTHS
    }
    if set(cells) != expected_cells:
        missing = sorted(expected_cells - set(cells))
        raise ValueError(f"scale evaluation has empty required cells: {missing}")

    per_scale: dict[str, Any] = {}
    for factor in SCALE_FACTORS:
        aggregate = _concatenate_cells(
            cells[(factor, length)] for length in PREFIX_LENGTHS
        )
        per_scale[f"{factor:g}"] = {
            "scale_factor": factor,
            **classification_report(
                aggregate.predictions,
                aggregate.labels,
                candidate.classes,
                aggregate.profiles,
            ),
        }
    per_length: dict[str, Any] = {}
    for length in PREFIX_LENGTHS:
        aggregate = _concatenate_cells(
            cells[(factor, length)] for factor in SCALE_FACTORS
        )
        per_length[str(length)] = {
            "prefix_length": length,
            **classification_report(
                aggregate.predictions,
                aggregate.labels,
                candidate.classes,
                aggregate.profiles,
            ),
        }
    pooled = _concatenate_cells(cells.values())
    pooled_report = classification_report(
        pooled.predictions,
        pooled.labels,
        candidate.classes,
        pooled.profiles,
    )

    scale_pairing: dict[str, Any] = {}
    for factor in SCALE_FACTORS:
        for length in PREFIX_LENGTHS:
            current = cells[(factor, length)]
            reference = cells[(SCALE_REFERENCE, length)]
            report = paired_invariance_report(
                current, reference, candidate.classes
            )
            key = f"scale={factor:g},length={length}"
            scale_pairing[key] = {
                "scale_factor": factor,
                "prefix_length": length,
                "reference_scale_factor": SCALE_REFERENCE,
                **report,
            }
    length_pairing: dict[str, Any] = {}
    for factor in SCALE_FACTORS:
        for length in PREFIX_LENGTHS:
            current = cells[(factor, length)]
            reference = cells[(factor, LENGTH_REFERENCE)]
            report = paired_invariance_report(
                current, reference, candidate.classes
            )
            key = f"scale={factor:g},length={length}"
            length_pairing[key] = {
                "scale_factor": factor,
                "prefix_length": length,
                "reference_prefix_length": LENGTH_REFERENCE,
                **report,
            }

    nonreference_scale = [
        report
        for report in scale_pairing.values()
        if report["scale_factor"] != SCALE_REFERENCE
    ]
    nonreference_length = [
        report
        for report in length_pairing.values()
        if report["prefix_length"] != LENGTH_REFERENCE
    ]
    cell_balanced = {
        key: float(report["present_class_balanced_accuracy"])
        for key, report in cell_reports.items()
    }
    profile_cell_accuracy = {
        f"{key},profile={profile}": float(profile_report["accuracy"])
        for key, report in cell_reports.items()
        for profile, profile_report in report["per_profile"].items()
    }
    legal_cell_counts = {
        key: int(report["count"]) for key, report in cell_reports.items()
    }
    missing_profile_cells: dict[str, list[str]] = {}
    profiles = sorted({row.profile for row in corpus.rows})
    for key, report in cell_reports.items():
        missing_profile_cells[key] = sorted(
            set(profiles) - set(report["per_profile"])
        )

    return {
        "pooled": pooled_report,
        "per_cell": cell_reports,
        "per_scale": per_scale,
        "per_length": per_length,
        "per_profile_pooled": pooled_report["per_profile"],
        "scale_pairing_to_native_rate": scale_pairing,
        "length_pairing_to_8192": length_pairing,
        "summary": {
            "worst_cell_present_class_balanced_accuracy": min(
                cell_balanced.values()
            ),
            "worst_cell_present_class_balanced_accuracy_cells": sorted(
                key
                for key, value in cell_balanced.items()
                if value == min(cell_balanced.values())
            ),
            "worst_scale_present_class_balanced_accuracy": min(
                float(report["present_class_balanced_accuracy"])
                for report in per_scale.values()
            ),
            "worst_length_present_class_balanced_accuracy": min(
                float(report["present_class_balanced_accuracy"])
                for report in per_length.values()
            ),
            "worst_profile_cell_accuracy": min(
                profile_cell_accuracy.values()
            ),
            "worst_profile_cell_accuracy_cells": sorted(
                key
                for key, value in profile_cell_accuracy.items()
                if value == min(profile_cell_accuracy.values())
            ),
            "worst_scale_prediction_agreement_to_native_rate": min(
                float(report["prediction_agreement"])
                for report in nonreference_scale
            ),
            "worst_scale_embedding_cosine_to_native_rate": min(
                float(report["embedding_cosine_mean"])
                for report in nonreference_scale
            ),
            "worst_length_prediction_agreement_to_8192": min(
                float(report["prediction_agreement"])
                for report in nonreference_length
            ),
            "worst_length_embedding_cosine_to_8192": min(
                float(report["embedding_cosine_mean"])
                for report in nonreference_length
            ),
        },
        "coverage": {
            "requested_scale_factors": list(SCALE_FACTORS),
            "requested_prefix_lengths": list(PREFIX_LENGTHS),
            "pair_count": int(corpus.audit["pair_count"]),
            "legal_cell_row_counts": legal_cell_counts,
            "missing_profiles_by_legal_cell": missing_profile_cells,
            "missing_cell_semantics": (
                "A profile is absent only when its bounded one-shot artifact "
                "cannot legally supply that prefix at that output rate. "
                "No zero-padded tail is used as evidence."
            ),
        },
        "geometry": geometry_reports,
        "decision_rule": (
            "minimum squared distance over current-source enrollment profile "
            "prototypes only; union-bank fallback is forbidden"
        ),
        "trusted_source_routing": {
            "kind": TRUSTED_SOURCE_ROUTING_KIND,
            "prototype_source": TRUSTED_PROTOTYPE_SOURCE,
            "reason": (
                "held scale corpus is produced by the bound current "
                "SignalLab 31-profile service path"
            ),
            "union_bank_fallback": False,
            "supported_public_classes": sorted(
                supported_by_trusted_source
            ),
        },
        "invariance_definitions": {
            "physical_scale": (
                "same service source coordinate and receiver realization; "
                "output sample rate requested at native/1.25x/1.5x/2x"
            ),
            "length": (
                "bit-exact admitted prefix of the same service measurement; "
                "paired to 8,192 samples"
            ),
            "frequency_transform_used": False,
        },
    }


def _source_hashes() -> dict[str, str]:
    paths = {
        "v4/evaluate_current_scale.py": Path(__file__).resolve(),
        "v4/current_source_data.py":
            Path(corpus_data.__file__).resolve(),
        "v4/assemble_current_source_fusion.py":
            HERE / "assemble_current_source_fusion.py",
        "v2/invariant_fusion.py": V2 / "invariant_fusion.py",
        "v2/invariant_patch_cnn.py": V2 / "invariant_patch_cnn.py",
        "training/time_domain_invariant_patch_preprocess.py":
            TRAINING / "time_domain_invariant_patch_preprocess.py",
        "training/time_domain_geometry.py":
            TRAINING / "time_domain_geometry.py",
        "training/invariant_patch_preprocess.py":
            TRAINING / "invariant_patch_preprocess.py",
    }
    return {
        name: _sha256(path)
        for name, path in sorted(paths.items())
        if path.is_file()
    }


def _assert_source_snapshot_unchanged(
    expected: Mapping[str, str],
    observed: Mapping[str, str],
) -> None:
    if dict(expected) == dict(observed):
        return
    changed = sorted(
        key
        for key in set(expected) | set(observed)
        if expected.get(key) != observed.get(key)
    )
    raise RuntimeError(
        "executed source changed during current scale evaluation: "
        + ", ".join(changed)
    )


def run(args: argparse.Namespace) -> dict[str, Any]:
    started = time.perf_counter()
    source_hashes_at_start = _source_hashes()
    output = reject_sensitive_path(args.output, "output")
    if output.exists():
        raise FileExistsError(f"refusing to overwrite evaluation: {output}")
    candidate = load_fusion_candidate(args.fusion_dir)
    corpus = load_scale_eval_corpus(
        args.eval_corpus,
        allow_unbound_smoke=args.allow_unbound_smoke,
    )
    current_audit = candidate.metrics["data_audit"]["current"]
    reference_audit = validate_reference_separation(
        corpus,
        args.reference_corpus,
        candidate_current_audit=current_audit,
    )
    device = device_runner.resolve_device(args.device)
    evaluation = evaluate(
        corpus,
        candidate,
        device,
        batch_size=args.batch_size,
    )
    result = {
        "status": "complete",
        "schema": EVALUATION_SCHEMA,
        "development_only": True,
        "release_evidence": False,
        "sealed_release_data_used": 0,
        "consumed_historical_test_rows_used": 0,
        "consumed_historical_test_rows_loaded": 0,
        "frequency_transforms_used": False,
        "candidate": {
            "directory": candidate.directory,
            "dev_metrics_sha256": _sha256(candidate.metrics_path),
            "artifact_sha256": candidate.artifact_hashes,
            "classes": candidate.classes,
            "architecture": candidate.metrics["architecture"],
            "frontend": candidate.metrics["frontend"],
            "trusted_source_routing": {
                "kind": TRUSTED_SOURCE_ROUTING_KIND,
                "prototype_source": TRUSTED_PROTOTYPE_SOURCE,
                "union_bank_fallback": False,
            },
        },
        "corpus": {
            "directory": corpus.directory,
            "audit": corpus.audit,
            "reference_separation": reference_audit,
            "generation_contract": {
                "physical_scale_method":
                    corpus.manifest["physicalScaleMethod"],
                "scale_pairing_rule": corpus.manifest["scalePairingRule"],
                "capture_bandwidth_rule":
                    corpus.manifest["captureBandwidthRule"],
                "pre_impairment_prefix_admission_rule":
                    corpus.manifest["preImpairmentPrefixAdmissionRule"],
                "informative_prefix_centered_rms_floor":
                    corpus.manifest["informativePrefixCenteredRmsFloor"],
                "scale_family_content_uniqueness_rule":
                    corpus.manifest["scaleFamilyContentUniquenessRule"],
                "one_shot_length_rule":
                    corpus.manifest["oneShotLengthRule"],
                "held_out_contract": corpus.manifest["heldOutContract"],
                "service_path": corpus.manifest["servicePath"],
                "low_level_synthesizer_calls": False,
            },
        },
        "evaluation": evaluation,
        "device": str(device),
        "batch_size": int(args.batch_size),
        "source_sha256": source_hashes_at_start,
        "wall_clock_s": time.perf_counter() - started,
    }
    _assert_source_snapshot_unchanged(
        source_hashes_at_start, _source_hashes()
    )
    _write_json_exclusive(output, result)
    print(f"[v4 current scale] wrote {output}", flush=True)
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--eval-corpus", required=True)
    parser.add_argument("--reference-corpus", required=True)
    parser.add_argument("--fusion-dir", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument(
        "--device", choices=("auto", "cpu", "mps"), default="auto"
    )
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument(
        "--allow-unbound-smoke",
        action="store_true",
        help=(
            "admit a generator UNBOUND_SMOKE corpus for code smoke only; "
            "reference/candidate hash checks still apply"
        ),
    )
    return parser


if __name__ == "__main__":
    run(build_parser().parse_args())
