"""NumPy port of Atom-DSP's propagation-channel model (src/channel.ts).

Atom-DSP's TypeScript is canonical. This port is gated by golden vectors
(`dsp-channel-conformance-vectors.json`, generated by
`gen-dsp-channel-vectors.mjs` from the pinned Atom-DSP revision) via
`test_dsp_channel_parity.py`: integer-exact hashes, <=1e-12 relative floats.

Semantics preserved from the TypeScript:
  * counter-based uint32 hash (JS `Math.imul`/`>>>` wrapping semantics);
  * closed-form in the absolute sample coordinate -- no PRNG stream state,
    so split and whole captures agree byte-for-byte;
  * application order: tapped-delay-line multipath, per-tap Rayleigh/Rician
    fading (Zheng & Xiao sum-of-sinusoids), AWGN at an absolute floor.

Vectorized entry points accept numpy index arrays. `fading_gain_grid`
additionally offers the corpus fast path: evaluate the closed-form gain on a
decimated absolute-coordinate grid and linearly interpolate. That is a
classifier-owned corpus policy (the decimation factor must be recorded in
the corpus manifest), not part of the Atom-DSP contract.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field

import numpy as np

BOLTZMANN_CONSTANT_J_PER_K = 1.380649e-23
STANDARD_NOISE_TEMPERATURE_K = 290.0

_NOISE_LANE_A = 0x6E6F6973
_NOISE_LANE_B = 0x656E6F69
_FADING_LANE_A = 0x66616469
_FADING_LANE_B = 0x6E675F62
_FADING_LANE_THETA = 0x74686574
_NOISE_INDEX_BIAS = 0x20000000
_FADING_SINUSOIDS = 16

_U32 = np.uint32
_TWO32 = float(1 << 32)


def thermal_noise_density_dbm_per_hz(
        noise_figure_db: float = 0.0,
        temperature_k: float = STANDARD_NOISE_TEMPERATURE_K) -> float:
    if temperature_k <= 0:
        raise ValueError("Noise temperature must be positive")
    milliwatts_per_hz = BOLTZMANN_CONSTANT_J_PER_K * temperature_k * 1_000
    return 10 * math.log10(milliwatts_per_hz) + noise_figure_db


def thermal_noise_floor_dbm(
        bandwidth_hz: float, noise_figure_db: float = 0.0,
        temperature_k: float = STANDARD_NOISE_TEMPERATURE_K) -> float:
    if bandwidth_hz <= 0:
        raise ValueError("Noise bandwidth must be positive")
    return (thermal_noise_density_dbm_per_hz(noise_figure_db, temperature_k)
            + 10 * math.log10(bandwidth_hz))


def _dbm_to_milliwatts(dbm) -> np.ndarray | float:
    return 10 ** (np.asarray(dbm, dtype=np.float64) / 10)


def channel_hash32(seed: int, index, lane: int) -> np.ndarray:
    """uint32 counter hash; `index` may be a scalar or int64 array (< 2^53)."""
    idx = np.asarray(index, dtype=np.int64)
    low = (idx & 0xFFFFFFFF).astype(_U32)
    high = (idx >> 32).astype(_U32)
    with np.errstate(over="ignore"):
        value = (_U32(seed & 0xFFFFFFFF) ^ _U32(lane & 0xFFFFFFFF)
                 ^ (low * _U32(0x9E3779B1)) ^ (high * _U32(0x85EBCA6B)))
        value ^= value >> _U32(16)
        value *= _U32(0x7FEB352D)
        value ^= value >> _U32(15)
        value *= _U32(0x846CA68B)
        value ^= value >> _U32(16)
    return value


def _seeded_uniform(seed: int, index, lane: int) -> np.ndarray:
    return (channel_hash32(seed, index, lane).astype(np.float64) + 0.5) / _TWO32


def seeded_complex_gaussian(seed: int, absolute_sample, lane: int = 0
                            ) -> tuple[np.ndarray, np.ndarray]:
    """Unit-variance-per-component complex Gaussian at absolute coordinates."""
    index = np.asarray(absolute_sample, dtype=np.int64) + _NOISE_INDEX_BIAS
    uniform_a = _seeded_uniform(seed, index, _NOISE_LANE_A ^ lane)
    uniform_b = _seeded_uniform(seed, index, _NOISE_LANE_B ^ lane)
    radius = np.sqrt(-2 * np.log(uniform_a))
    angle = 2 * np.pi * uniform_b
    return radius * np.cos(angle), radius * np.sin(angle)


TDL_A = ((0.0000, -13.4), (0.3819, 0.0), (0.4025, -2.2), (0.5868, -4.0),
         (0.4610, -6.0), (0.5375, -8.2), (0.6708, -9.9), (0.5750, -10.5),
         (0.7618, -7.5), (1.5375, -15.9), (1.8978, -6.6), (2.2242, -16.7))
TDL_B = ((0.0000, 0.0), (0.1072, -2.2), (0.2155, -4.0), (0.2095, -3.2),
         (0.2870, -9.8), (0.2986, -1.2), (0.3752, -3.4), (0.5055, -5.2),
         (0.3681, -7.6), (0.3697, -3.0), (0.5700, -8.9), (0.5283, -9.0))
TDL_D = ((0.0000, -0.2), (0.0350, -18.8), (0.6120, -21.0), (1.3630, -22.8),
         (1.4050, -17.9), (2.5960, -20.1), (1.7750, -21.9), (4.0420, -22.9),
         (7.9370, -27.8), (9.4240, -23.6), (9.7080, -24.8))
TDL_PROFILES = {"tdl-a": TDL_A, "tdl-b": TDL_B, "tdl-d": TDL_D}


def resolve_tdl_taps(profile, delay_spread_seconds: float,
                     sample_rate_hz: float) -> list[dict]:
    """[{delaySamples, powerDb}], unit total power, JS half-up rounding."""
    if delay_spread_seconds < 0:
        raise ValueError("Delay spread must be non-negative")
    if sample_rate_hz <= 0:
        raise ValueError("Sample rate must be positive")
    taps = TDL_PROFILES[profile] if isinstance(profile, str) else profile
    combined: dict[int, float] = {}
    for normalized_delay, power_db in taps:
        # JS Math.round: half away from zero for positive arguments.
        delay = math.floor(
            normalized_delay * delay_spread_seconds * sample_rate_hz + 0.5)
        combined[delay] = combined.get(delay, 0.0) + float(
            _dbm_to_milliwatts(power_db))
    total = sum(combined.values())
    return [{"delaySamples": d, "powerDb": 10 * math.log10(mw / total)}
            for d, mw in sorted(combined.items())]


@dataclass(frozen=True)
class FadingConfiguration:
    kind: str                       # 'rayleigh' | 'rician'
    doppler_hz: float
    k_factor_db: float | None = None


def fading_gain_at_time(configuration: FadingConfiguration, seed: int,
                        tap_index: int, time_seconds
                        ) -> tuple[np.ndarray, np.ndarray]:
    """Zheng & Xiao sum-of-sinusoids gain; `time_seconds` may be an array."""
    if configuration.doppler_hz < 0:
        raise ValueError("Doppler shift must be non-negative")
    t = np.asarray(time_seconds, dtype=np.float64)
    theta = 2 * np.pi * float(
        _seeded_uniform(seed, tap_index, _FADING_LANE_THETA)) - np.pi
    real = np.zeros_like(t)
    imaginary = np.zeros_like(t)
    omega = 2 * np.pi * configuration.doppler_hz * t
    for m in range(1, _FADING_SINUSOIDS + 1):
        key = tap_index * 0x10000 + m
        alpha = (2 * np.pi * m - np.pi + theta) / (4 * _FADING_SINUSOIDS)
        phi = 2 * np.pi * float(_seeded_uniform(seed, key, _FADING_LANE_A)) - np.pi
        psi = 2 * np.pi * float(_seeded_uniform(seed, key, _FADING_LANE_B)) - np.pi
        real += np.cos(omega * np.cos(alpha) + phi)
        imaginary += np.cos(omega * np.sin(alpha) + psi)
    scale = math.sqrt(1 / _FADING_SINUSOIDS)
    diffuse_real = scale * real
    diffuse_imaginary = scale * imaginary
    if configuration.kind == "rayleigh":
        return diffuse_real, diffuse_imaginary
    k_factor = 10 ** ((configuration.k_factor_db or 0.0) / 10)
    specular_weight = math.sqrt(k_factor / (k_factor + 1))
    diffuse_weight = math.sqrt(1 / (k_factor + 1))
    specular_phase = (2 * np.pi * configuration.doppler_hz * t
                      * math.cos(theta))
    return (specular_weight * np.cos(specular_phase)
            + diffuse_weight * diffuse_real,
            specular_weight * np.sin(specular_phase)
            + diffuse_weight * diffuse_imaginary)


def fading_gain_grid(configuration: FadingConfiguration, seed: int,
                     tap_index: int, start_index: int, count: int,
                     sample_rate_hz: float, grid_step: int
                     ) -> np.ndarray:
    """Corpus fast path: exact gains on a decimated absolute-coordinate grid,
    linearly interpolated to per-sample complex gains. grid_step=1 is exact.
    The grid is anchored at absolute index 0, so any [start, start+count)
    window of one stream draws identical gains regardless of how the stream
    is split. Record grid_step in the corpus manifest."""
    if grid_step < 1:
        raise ValueError("grid_step must be >= 1")
    first = (start_index // grid_step)
    last = ((start_index + count - 1) // grid_step) + 1
    grid_indices = np.arange(first, last + 1, dtype=np.int64) * grid_step
    gain_r, gain_i = fading_gain_at_time(
        configuration, seed, tap_index,
        grid_indices.astype(np.float64) / sample_rate_hz)
    gains = gain_r + 1j * gain_i
    if grid_step == 1:
        return gains[start_index - grid_indices[0]:
                     start_index - grid_indices[0] + count]
    sample_indices = np.arange(start_index, start_index + count,
                               dtype=np.int64)
    position = (sample_indices - grid_indices[0]) / grid_step
    base = np.floor(position).astype(np.int64)
    frac = position - base
    return gains[base] * (1 - frac) + gains[base + 1] * frac


def noise_standard_deviation(noise_floor_dbm: float,
                             full_scale_dbm: float = 0.0) -> float:
    relative_power = float(_dbm_to_milliwatts(noise_floor_dbm - full_scale_dbm))
    return math.sqrt(relative_power / 2)


@dataclass(frozen=True)
class ChannelConfiguration:
    noise_floor_dbm: float
    seed: int
    sample_rate_hz: float
    full_scale_dbm: float = 0.0
    taps: tuple = field(default_factory=lambda: ({"delaySamples": 0,
                                                  "powerDb": 0.0},))
    fading: FadingConfiguration | None = None


def apply_channel_at_index(source_at, absolute_sample_index: int,
                           configuration: ChannelConfiguration
                           ) -> tuple[float, float]:
    """Scalar reference implementation, matching the TypeScript verbatim.
    Use apply_channel_to_row for corpus work."""
    real = 0.0
    imaginary = 0.0
    for tap_index, tap in enumerate(configuration.taps):
        delayed = absolute_sample_index - tap["delaySamples"]
        if delayed < 0:
            continue
        source_real, source_imaginary = source_at(delayed)
        amplitude = math.sqrt(float(_dbm_to_milliwatts(tap["powerDb"])))
        gain_real, gain_imaginary = amplitude, 0.0
        if configuration.fading is not None:
            fade_r, fade_i = fading_gain_at_time(
                configuration.fading, configuration.seed, tap_index,
                absolute_sample_index / configuration.sample_rate_hz)
            gain_real = amplitude * float(fade_r)
            gain_imaginary = amplitude * float(fade_i)
        real += source_real * gain_real - source_imaginary * gain_imaginary
        imaginary += (source_real * gain_imaginary
                      + source_imaginary * gain_real)
    deviation = noise_standard_deviation(configuration.noise_floor_dbm,
                                         configuration.full_scale_dbm)
    if deviation > 0:
        noise_r, noise_i = seeded_complex_gaussian(
            configuration.seed, absolute_sample_index)
        real += deviation * float(noise_r)
        imaginary += deviation * float(noise_i)
    return real, imaginary


def apply_channel_to_row(row: np.ndarray,
                         configuration: ChannelConfiguration,
                         fading_grid_step: int = 1,
                         add_noise: bool = True) -> np.ndarray:
    """Vectorized channel application to one complex row (row-local
    coordinates; index 0 is the row's first sample). Pre-row samples are
    treated as silence, matching the TypeScript's delayed<0 skip."""
    n = len(row)
    out = np.zeros(n, dtype=np.complex128)
    for tap_index, tap in enumerate(configuration.taps):
        delay = int(tap["delaySamples"])
        if delay >= n:
            continue
        amplitude = math.sqrt(float(_dbm_to_milliwatts(tap["powerDb"])))
        delayed = np.zeros(n, dtype=np.complex128)
        delayed[delay:] = row[:n - delay]
        if configuration.fading is not None:
            gains = fading_gain_grid(
                configuration.fading, configuration.seed, tap_index,
                0, n, configuration.sample_rate_hz, fading_grid_step)
            out += delayed * (amplitude * gains)
        else:
            out += delayed * amplitude
    if add_noise:
        deviation = noise_standard_deviation(configuration.noise_floor_dbm,
                                             configuration.full_scale_dbm)
        if deviation > 0:
            noise_r, noise_i = seeded_complex_gaussian(
                configuration.seed, np.arange(n, dtype=np.int64))
            out += deviation * (noise_r + 1j * noise_i)
    return out
