/* Generated by tools/train-observable-classifier.ts; do not hand edit. */
export const BAYESIAN_OBSERVABLE_MODEL_SHA256 = '6e99889881f06f43ba10307f2e98f5c44cc17a684f783f40d7c2153c4c6c6f7e' as const;
export const BAYESIAN_OBSERVABLE_MODEL_CONTENT_SHA256 = 'a0d05c6818ed6c0ace9a266629153768d761027ebd8383990eca4210e9a20c21' as const;
