/* Generated by tools/train-observable-classifier.ts; do not hand edit. */
export const BAYESIAN_OBSERVABLE_MODEL_SHA256 = '6e25efced19690b599745000fe6b0ea46ca1af67220bb3b2b3b691b9bcf2ffe4' as const;
export const BAYESIAN_OBSERVABLE_MODEL_CONTENT_SHA256 = '2b0a5018e1b5578a73b339b2ad95e458fc6809571a058041bfd3c0f8ec922bf3' as const;
